// Copyright 2018, Cristián Donoso.
// This code has a BSD license. See LICENSE.

#include "src/platform/platform.h"

#include <windows.h>

#include "src/utils/log.h"
#include "src/utils/path.h"

namespace warhol {

std::string Platform::GetCurrentExecutablePath() {
  // Get the executable handle.
  HMODULE exe_module = GetModuleHandleA(NULL);
  char path[MAX_PATH];
  GetModuleFileName(exe_module, path, MAX_PATH);

  return path;
}

std::string Platform::GetBasePath() {
  std::string exe_path = GetCurrentExecutablePath();
  // First search for a last '/' (path probably generated by Warhol itself).
  // If not, see if it's a normal Windows path.
  size_t separator = exe_path.rfind('\\');
  if (separator == std::string::npos)
    separator = exe_path.rfind('\\');

  if (separator == std::string::npos)
    return exe_path;
  auto base_path = exe_path.substr(0, separator);
  return PathJoin({std::move(base_path), ".."});
}

}  // namespace warhol
